### PR TITLE
Remove Gemfile.lock

### PR DESCRIPTION
**Pull request by bananaappletw**
### Describe the change
Remove Gemfile.lock

### Why are we doing this?
Prepare for bundler 2.x.x

### Benefits
For the future

### Drawbacks
None

### Requirements
Put an X between brackets on each line if you have done the item:
[X] Tests written & passing locally?
[X] Code style checked?
[X] Rebased with `master` branch?
[] Documentaion updated?

### CODE REVIEW

**Comment by bananaappletw** [comment]
@piotrmurach 
Try couple of hours, jruby seems not work with system bundler on travis ci.
Couldn't find the way to resolve it.

**Comment by piotrmurach** [comment]
Thanks ❤️

**Comment by bananaappletw** [comment]
@piotrmurach 
Could you also make a release for gem?
Thank you.

**Comment by piotrmurach** [comment]
@bananaappletw Why release? Have I missed something?

**Comment by bananaappletw** [comment]
@piotrmurach 
Because `Gemfile.lock` will limit the dependencies when using the gem.
My release means gem version `v0.8.0` => `v0.8.1`.
Thank you.

**Comment by piotrmurach** [comment]
@bananaappletw Ah I see why this confusion. The `Gemfile.lock` will not limit the dependencies when using the gem. `Gemfile.lock` is not used during gem installation via `rubygems`. The only thing that matters is the `gemspec` specified [runtime dependency](https://github.com/piotrmurach/loaf/blob/master/loaf.gemspec#L24). In this gem's case, the runtime dependency is `rails >= 3.2`. I use this gem just fine in Rails `5.2`. In my Rails project's Gemfile:

```ruby
gem 'loaf', '~> 0.8.0'
```
works perfectly fine.

The reason for the `Gemfile` and `Gemfile.lock` existence in this project is to ease the development when checking out actual git repository. This is also the case when CI tests are run which actually clone the repository from GitHub. 

So there is no need to realease anything as this is a purely development setup. Similar to other configuration files in this project.

**Comment by bananaappletw** [comment]
@piotrmurach You are correct. If `loaf` installed by Gemfile, the `rake` version will be `12.3.2`.
But If I run `gem install loaf`, my `rake` will be conflicted with `loaf`'s `rake` version.
Although, it's doesn't matter at all, sorry to be stubborn.
Thank you for the reply.

```bash
bash-4.4# gem install rake
Successfully installed rake-12.3.2
1 gem installed
bash-4.4# gem install loaf
loaf's executable "rake" conflicts with rake
Overwrite the executable? [yN]  y
Successfully installed loaf-0.8.0
1 gem installed
```

**Comment by piotrmurach** [comment]
@bananaappletw All is good. You're welcome to ask me things, suggest solutions and I'm really glad you do. Discussion is healthy!

The `rake` issue that you just pointed out is a different matter and willl actually require a new release. I don't believe `rake` version has anything to do with it. For some reason, this project adds wrappers around `rake`, `appraisal` [binaries](https://github.com/piotrmurach/loaf/tree/master/bin) which then conflict with system wide install of `rake`. I will resolve it shortly!

**Comment by piotrmurach** [comment]
@bananaappletw Released `v0.8.1` that fixes this issue.

**Comment by bananaappletw** [comment]
@piotrmurach 
Thank you so much.

**Pull request merged**
