### PR TITLE
Remove Gemfile.lock

### PR DESCRIPTION
**Pull request by bananaappletw**
### Describe the change
Remove Gemfile.lock

### Why are we doing this?

https://bundler.io/man/bundle-install.1.html#THE-GEMFILE-LOCK

### Benefits
Gem dependencies won't be determined by `Gemfile.lock`

### Drawbacks
None

### Requirements
Put an X between brackets on each line if you have done the item:
[] Tests written & passing locally?
[] Code style checked?
[X] Rebased with `master` branch?
[] Documentaion updated?

### CODE REVIEW

**Comment by bananaappletw** [comment]
This happens when bundler is greater than 1.x
For example, 2.0.1

**Comment by bananaappletw** [comment]
I don't know how to deal with `bundler` greater than `2.0.1`
Could you help me to fix it?

**Comment by piotrmurach** [comment]
So the issue is that tests fail on jruby? If that's the case I honestly don't know how to configure travis to force it to use `bundler` less than `v2.0` on jruby. My current solution is to do similar thing to you `gem install bundler -v 1.17.3` but it still doesn't make tests pass on jruby. It seems that your fix works for the `mri` rubies and it is important to support  older rubies for older versions of Rails. Your patch seems to work on all the requried rubies so I'm ok with it. If you manage to find a fix for jruby that's great but don't worry about it too much I will merge anyway.

**Comment by bananaappletw** [comment]
@piotrmurach 
Yes.

**Pull request closed without merging**
